// Orb variants: the model picks one by name (⟦orb:name⟧). Read by orb.js (<script>) and agent/orb.mjs (the JSON between [ and ]).
// shape = SDF id in orb.js, mood = calm|spiky|jitter|shards|pulse, hue = color override or null, hint = word for the prompt.
var ORB_VARIANTS = [
  {"name": "blob", "shape": "blob", "mood": "calm", "hue": null, "hint": "neutro"},
  {"name": "spinoso", "shape": "blob", "mood": "spiky", "hue": null, "hint": "problema, tensione"},
  {"name": "tremolante", "shape": "blob", "mood": "jitter", "hue": null, "hint": "incertezza"},
  {"name": "frammentato", "shape": "blob", "mood": "shards", "hue": null, "hint": "più cose insieme"},
  {"name": "impulsi", "shape": "blob", "mood": "pulse", "hue": null, "hint": "energia"},
  {"name": "lente", "shape": "lens", "mood": "calm", "hue": null, "hint": "ricerca"},
  {"name": "globo", "shape": "globe", "mood": "calm", "hue": null, "hint": "web, browser"},
  {"name": "busta", "shape": "envelope", "mood": "calm", "hue": null, "hint": "mail"},
  {"name": "ingranaggio", "shape": "gear", "mood": "calm", "hue": null, "hint": "configurazione"},
  {"name": "terminale", "shape": "terminal", "mood": "calm", "hue": null, "hint": "comandi"},
  {"name": "matita", "shape": "pencil", "mood": "calm", "hue": null, "hint": "scrivere, modificare"},
  {"name": "documento", "shape": "document", "mood": "calm", "hue": null, "hint": "leggere file"},
  {"name": "cartella", "shape": "folder", "mood": "calm", "hue": null, "hint": "file, drive"},
  {"name": "calendario", "shape": "calendar", "mood": "calm", "hue": null, "hint": "agenda"},
  {"name": "tavolozza", "shape": "palette", "mood": "calm", "hue": null, "hint": "design"},
  {"name": "robot-retro", "shape": "robot", "mood": "calm", "hue": null, "hint": "sub-agente, automazione"},
  {"name": "persona", "shape": "person", "mood": "calm", "hue": null, "hint": "contatti, meeting"},
  {"name": "simbionte", "shape": "symbiote", "mood": "calm", "hue": "#101018", "hint": "lavoro lungo e autonomo"},
  {"name": "bussola", "shape": "compass", "mood": "calm", "hue": null, "hint": "orientarsi, direzioni"},
  {"name": "binocolo", "shape": "binoculars", "mood": "calm", "hue": null, "hint": "esplorare, osservare"},
  {"name": "radar", "shape": "radar", "mood": "calm", "hue": null, "hint": "monitorare, scansione"},
  {"name": "fumetto", "shape": "speech", "mood": "calm", "hue": null, "hint": "chat, messaggi"},
  {"name": "telefono", "shape": "phone", "mood": "calm", "hue": null, "hint": "chiamate, sms"},
  {"name": "megafono", "shape": "megaphone", "mood": "calm", "hue": null, "hint": "annunci, pubblicare"},
  {"name": "aereo-carta", "shape": "paperplane", "mood": "calm", "hue": null, "hint": "inviare"},
  {"name": "graffe", "shape": "braces", "mood": "calm", "hue": null, "hint": "codice, json"},
  {"name": "chiave-inglese", "shape": "wrench", "mood": "calm", "hue": null, "hint": "riparare, sistemare"},
  {"name": "insetto", "shape": "bug", "mood": "calm", "hue": null, "hint": "debug, bug"},
  {"name": "razzo", "shape": "rocket", "mood": "calm", "hue": null, "hint": "deploy, rilascio"},
  {"name": "ramo-git", "shape": "gitbranch", "mood": "calm", "hue": null, "hint": "git, branch, merge"},
  {"name": "libro", "shape": "book", "mood": "calm", "hue": null, "hint": "documentazione, studiare"},
  {"name": "graffetta", "shape": "paperclip", "mood": "calm", "hue": null, "hint": "allegati"},
  {"name": "cestino", "shape": "trash", "mood": "calm", "hue": null, "hint": "eliminare, pulire"},
  {"name": "scatola", "shape": "box3d", "mood": "calm", "hue": null, "hint": "pacchetti, installare"},
  {"name": "orologio", "shape": "clock", "mood": "calm", "hue": null, "hint": "orario, tempo"},
  {"name": "clessidra", "shape": "hourglass", "mood": "calm", "hue": null, "hint": "attesa, scadenza"},
  {"name": "sveglia", "shape": "alarm", "mood": "calm", "hue": null, "hint": "promemoria, sveglia, timer"},
  {"name": "grafico", "shape": "chart", "mood": "calm", "hue": null, "hint": "dati, statistiche, report"},
  {"name": "moneta", "shape": "coin", "mood": "calm", "hue": "#f5b82e", "hint": "soldi, prezzi, spese"},
  {"name": "carrello", "shape": "cart", "mood": "calm", "hue": null, "hint": "acquisti, spesa, ordini"},
  {"name": "salvadanaio", "shape": "piggy", "mood": "calm", "hue": null, "hint": "risparmi, budget"},
  {"name": "calcolatrice", "shape": "calculator", "mood": "calm", "hue": null, "hint": "calcoli, conti"},
  {"name": "nota-musicale", "shape": "note", "mood": "calm", "hue": null, "hint": "musica, playlist"},
  {"name": "cuffie", "shape": "headphones", "mood": "calm", "hue": null, "hint": "ascoltare, audio, podcast"},
  {"name": "fotocamera", "shape": "camera", "mood": "calm", "hue": null, "hint": "foto, screenshot, immagini"},
  {"name": "pellicola", "shape": "film", "mood": "calm", "hue": null, "hint": "video, film, serie"},
  {"name": "microfono", "shape": "mic", "mood": "calm", "hue": null, "hint": "registrare, dettatura, voce"},
  {"name": "sole", "shape": "sun", "mood": "calm", "hue": "#ffb020", "hint": "meteo sereno, mattina"},
  {"name": "nuvola", "shape": "cloud", "mood": "calm", "hue": null, "hint": "meteo nuvoloso, cloud"},
  {"name": "pioggia", "shape": "rain", "mood": "calm", "hue": null, "hint": "meteo pioggia"},
  {"name": "fulmine", "shape": "bolt", "mood": "calm", "hue": "#ffd23a", "hint": "temporale, veloce, energia"},
  {"name": "fiocco-neve", "shape": "snowflake", "mood": "calm", "hue": null, "hint": "neve, freddo, inverno"},
  {"name": "luna", "shape": "moon", "mood": "calm", "hue": "#e8dca0", "hint": "notte, sera, riposo"},
  {"name": "fiamma", "shape": "flame", "mood": "calm", "hue": "#ff7a1a", "hint": "urgente, caldo, trend"},
  {"name": "foglia", "shape": "leaf", "mood": "calm", "hue": "#58c46a", "hint": "natura, ambiente, piante"},
  {"name": "goccia", "shape": "drop", "mood": "calm", "hue": "#3ea8ff", "hint": "acqua, liquidi, umidità"},
  {"name": "casa", "shape": "house", "mood": "calm", "hue": null, "hint": "casa, domotica"},
  {"name": "lampadina", "shape": "bulb", "mood": "calm", "hue": null, "hint": "idea, luci"},
  {"name": "tazza-caffe", "shape": "mug", "mood": "calm", "hue": null, "hint": "pausa, mattina"},
  {"name": "chiave", "shape": "key", "mood": "calm", "hue": null, "hint": "accesso, password"},
  {"name": "lucchetto", "shape": "lock", "mood": "calm", "hue": null, "hint": "sicurezza, permessi"},
  {"name": "campanella", "shape": "bell", "mood": "calm", "hue": null, "hint": "notifiche, promemoria"},
  {"name": "regalo", "shape": "gift", "mood": "calm", "hue": null, "hint": "regali, compleanni"},
  {"name": "cuore", "shape": "heart", "mood": "calm", "hue": "#ff4d6d", "hint": "affetti, salute, preferiti"},
  {"name": "stella", "shape": "star", "mood": "calm", "hue": "#ffc53d", "hint": "preferiti, valutazioni"},
  {"name": "bandiera", "shape": "flag", "mood": "calm", "hue": null, "hint": "obiettivi, traguardi"},
  {"name": "puntina-mappa", "shape": "pin", "mood": "calm", "hue": null, "hint": "luoghi, mappe, indirizzi"},
  {"name": "auto", "shape": "car", "mood": "calm", "hue": null, "hint": "viaggio, traffico, spostamenti"},
  {"name": "trofeo", "shape": "trophy", "mood": "calm", "hue": "#f5b700", "hint": "risultati, vittorie"},
  {"name": "dado", "shape": "dice", "mood": "calm", "hue": null, "hint": "caso, giochi, scelta casuale"},
  {"name": "puzzle", "shape": "puzzle", "mood": "calm", "hue": null, "hint": "integrazioni, plugin, problemi da risolvere"},
  {"name": "cervello", "shape": "brain", "mood": "calm", "hue": null, "hint": "ragionamento, memoria, note"},
  {"name": "occhio", "shape": "eye", "mood": "calm", "hue": null, "hint": "osservare, schermo, revisione"},
  {"name": "pollice-su", "shape": "thumbsup", "mood": "calm", "hue": null, "hint": "approvazione, ok"},
  {"name": "spunta", "shape": "check", "mood": "calm", "hue": null, "hint": "fatto, completato, todo"},
  {"name": "idraulico-baffi", "shape": "plumber", "mood": "calm", "hue": null, "hint": "riparare, sistemare un guasto"},
  {"name": "fantasmino-arcade", "shape": "ghost", "mood": "calm", "hue": "#ff5a7a", "hint": "gioco, cosa sparita o nascosta"},
  {"name": "mangia-pallini", "shape": "chomper", "mood": "calm", "hue": "#ffd21f", "hint": "macinare tanti elementi, pulizia"},
  {"name": "invasore-pixel", "shape": "invader", "mood": "calm", "hue": "#39ff7a", "hint": "retro, videogiochi, attacco"},
  {"name": "astronauta-fagiolo", "shape": "bean", "mood": "calm", "hue": null, "hint": "esplorare, indagare chi è stato"},
  {"name": "supereroe-mantello", "shape": "hero", "mood": "calm", "hue": null, "hint": "salvataggio, urgenza risolta"},
  {"name": "cavaliere", "shape": "knight", "mood": "calm", "hue": null, "hint": "difesa, sicurezza, protezione"},
  {"name": "ninja", "shape": "ninja", "mood": "calm", "hue": "#2a2d3a", "hint": "operazione furtiva, veloce"},
  {"name": "mago", "shape": "wizard", "mood": "calm", "hue": null, "hint": "magia, generare, trasformare"},
  {"name": "zombie", "shape": "zombie", "mood": "calm", "hue": "#6fbf5a", "hint": "processo bloccato, codice morto"},
  {"name": "pirata", "shape": "pirate", "mood": "calm", "hue": null, "hint": "scaricare, tesoro, avventura"},
  {"name": "vampiro", "shape": "vampire", "mood": "calm", "hue": "#7a1030", "hint": "notte, risorse che succhiano memoria"},
  {"name": "alieno", "shape": "alien", "mood": "calm", "hue": "#9aa7b0", "hint": "cosa strana, sconosciuta"},
  {"name": "scheletro", "shape": "skeleton", "mood": "calm", "hue": "#e8e4d8", "hint": "struttura, scheletro di progetto, halloween"},
  {"name": "detective", "shape": "detective", "mood": "calm", "hue": null, "hint": "indagine, debug, trovare la causa"},
  {"name": "cowboy", "shape": "cowboy", "mood": "calm", "hue": null, "hint": "west, avventura"},
  {"name": "gatto", "shape": "cat", "mood": "calm", "hue": null, "hint": "animali, relax"},
  {"name": "cane", "shape": "dog", "mood": "calm", "hue": null, "hint": "animali, fedeltà, recuperare"},
  {"name": "gufo", "shape": "owl", "mood": "calm", "hue": null, "hint": "saggezza, notte, studio"},
  {"name": "drago", "shape": "dragon", "mood": "calm", "hue": null, "hint": "potenza, fantasy, compito epico"},
  {"name": "dinosauro", "shape": "dino", "mood": "calm", "hue": null, "hint": "vecchio, legacy, storia"},
  {"name": "polpo", "shape": "octopus", "mood": "calm", "hue": null, "hint": "multitasking, tante cose insieme"},
  {"name": "pinguino", "shape": "penguin", "mood": "calm", "hue": null, "hint": "linux, freddo, inverno"},
  {"name": "unicorno", "shape": "unicorn", "mood": "calm", "hue": "#e58ff0", "hint": "magia, raro, idea speciale"},
  {"name": "slime", "shape": "slime", "mood": "calm", "hue": "#35d07f", "hint": "gioco, rpg, pasticcio"},
  {"name": "fungo-bonus", "shape": "mushroom", "mood": "calm", "hue": "#e0413a", "hint": "bonus, crescita, potenziamento"},
  {"name": "blocco-bonus", "shape": "qblock", "mood": "calm", "hue": "#f0b429", "hint": "sorpresa, domanda, mistero"}
];
